// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: Copyright 2025 Airbus Defence and Space
// SPDX-FileContributor: Patrick Siegl <patrick.siegl@airbus.com>

#include "apex_host_fncs_wasm32.h"
#include "arinc653_part1_apex_time_wasm32.h"
#include "arinc653_part1_apex_process_wasm32.h"
#include "arinc653_part1_apex_partition_wasm32.h"
#include "arinc653_part1_apex_sampling_port_wasm32.h"
#include "arinc653_part1_apex_queuing_port_wasm32.h"
#include "arinc653_part1_apex_buffer_wasm32.h"
#include "arinc653_part1_apex_blackboard_wasm32.h"
#include "arinc653_part1_apex_semaphore_wasm32.h"
#include "arinc653_part1_apex_event_wasm32.h"
#include "arinc653_part1_apex_mutex_wasm32.h"
#include "arinc653_part1_apex_error_wasm32.h"
#include "arinc653_part2_apex_sampling_port_extension_wasm32.h"

#define WASM_HOSTFUNC_SIGNATURE( FNC ) { #FNC, WASM32_##FNC, WASM32_SIGNATURE__##FNC, NULL }
static NativeSymbol native_symbols[] = {
/* APEX (ARINC 653 Part 1): TIME */
  WASM_HOSTFUNC_SIGNATURE( TIMED_WAIT ),
  WASM_HOSTFUNC_SIGNATURE( PERIODIC_WAIT ),
  WASM_HOSTFUNC_SIGNATURE( GET_TIME ),
  WASM_HOSTFUNC_SIGNATURE( REPLENISH ),
/* APEX (ARINC 653 Part 1): PROCESS */
  WASM_HOSTFUNC_SIGNATURE( CREATE_PROCESS ),
  WASM_HOSTFUNC_SIGNATURE( SET_PRIORITY ),
  WASM_HOSTFUNC_SIGNATURE( SUSPEND_SELF ),
  WASM_HOSTFUNC_SIGNATURE( SUSPEND ),
  WASM_HOSTFUNC_SIGNATURE( RESUME ),
  WASM_HOSTFUNC_SIGNATURE( STOP_SELF ),
  WASM_HOSTFUNC_SIGNATURE( STOP ),
  WASM_HOSTFUNC_SIGNATURE( START ),
  WASM_HOSTFUNC_SIGNATURE( DELAYED_START ),
  WASM_HOSTFUNC_SIGNATURE( LOCK_PREEMPTION ),
  WASM_HOSTFUNC_SIGNATURE( UNLOCK_PREEMPTION ),
  WASM_HOSTFUNC_SIGNATURE( GET_MY_ID ),
  WASM_HOSTFUNC_SIGNATURE( GET_PROCESS_ID ),
  WASM_HOSTFUNC_SIGNATURE( GET_PROCESS_STATUS ),
  WASM_HOSTFUNC_SIGNATURE( INITIALIZE_PROCESS_CORE_AFFINITY ),
  WASM_HOSTFUNC_SIGNATURE( GET_MY_PROCESSOR_CORE_ID ),
  WASM_HOSTFUNC_SIGNATURE( GET_MY_INDEX ),
/* APEX (ARINC 653 Part 1): PARTITION */
  WASM_HOSTFUNC_SIGNATURE( GET_PARTITION_STATUS ),
  WASM_HOSTFUNC_SIGNATURE( SET_PARTITION_MODE ),
/* APEX (ARINC 653 Part 1): SAMPLING PORT */
  WASM_HOSTFUNC_SIGNATURE( CREATE_SAMPLING_PORT ),
  WASM_HOSTFUNC_SIGNATURE( WRITE_SAMPLING_MESSAGE ),
  WASM_HOSTFUNC_SIGNATURE( READ_SAMPLING_MESSAGE ),
  WASM_HOSTFUNC_SIGNATURE( GET_SAMPLING_PORT_ID ),
  WASM_HOSTFUNC_SIGNATURE( GET_SAMPLING_PORT_STATUS ),
/* APEX (ARINC 653 Part 1): QUEUING PORT */
  WASM_HOSTFUNC_SIGNATURE( CREATE_QUEUING_PORT ),
  WASM_HOSTFUNC_SIGNATURE( SEND_QUEUING_MESSAGE ),
  WASM_HOSTFUNC_SIGNATURE( RECEIVE_QUEUING_MESSAGE ),
  WASM_HOSTFUNC_SIGNATURE( GET_QUEUING_PORT_ID ),
  WASM_HOSTFUNC_SIGNATURE( GET_QUEUING_PORT_STATUS ),
  WASM_HOSTFUNC_SIGNATURE( CLEAR_QUEUING_PORT ),
/* APEX (ARINC 653 Part 1): BUFFER */
  WASM_HOSTFUNC_SIGNATURE( CREATE_BUFFER ),
  WASM_HOSTFUNC_SIGNATURE( SEND_BUFFER ),
  WASM_HOSTFUNC_SIGNATURE( RECEIVE_BUFFER ),
  WASM_HOSTFUNC_SIGNATURE( GET_BUFFER_ID ),
  WASM_HOSTFUNC_SIGNATURE( GET_BUFFER_STATUS ),
/* APEX (ARINC 653 Part 1): BLACKBOARD */
  WASM_HOSTFUNC_SIGNATURE( CREATE_BLACKBOARD ),
  WASM_HOSTFUNC_SIGNATURE( DISPLAY_BLACKBOARD ),
  WASM_HOSTFUNC_SIGNATURE( READ_BLACKBOARD ),
  WASM_HOSTFUNC_SIGNATURE( CLEAR_BLACKBOARD ),
  WASM_HOSTFUNC_SIGNATURE( GET_BLACKBOARD_ID ),
  WASM_HOSTFUNC_SIGNATURE( GET_BLACKBOARD_STATUS ),
/* APEX (ARINC 653 Part 1): SEMAPHORE */
  WASM_HOSTFUNC_SIGNATURE( CREATE_SEMAPHORE ),
  WASM_HOSTFUNC_SIGNATURE( WAIT_SEMAPHORE ),
  WASM_HOSTFUNC_SIGNATURE( SIGNAL_SEMAPHORE ),
  WASM_HOSTFUNC_SIGNATURE( GET_SEMAPHORE_ID ),
  WASM_HOSTFUNC_SIGNATURE( GET_SEMAPHORE_STATUS ),
/* APEX (ARINC 653 Part 1): EVENT */
  WASM_HOSTFUNC_SIGNATURE( CREATE_EVENT ),
  WASM_HOSTFUNC_SIGNATURE( SET_EVENT ),
  WASM_HOSTFUNC_SIGNATURE( RESET_EVENT ),
  WASM_HOSTFUNC_SIGNATURE( WAIT_EVENT ),
  WASM_HOSTFUNC_SIGNATURE( GET_EVENT_ID ),
  WASM_HOSTFUNC_SIGNATURE( GET_EVENT_STATUS ),
/* APEX (ARINC 653 Part 1): MUTEX */
  WASM_HOSTFUNC_SIGNATURE( CREATE_MUTEX ),
  WASM_HOSTFUNC_SIGNATURE( ACQUIRE_MUTEX ),
  WASM_HOSTFUNC_SIGNATURE( RELEASE_MUTEX ),
  WASM_HOSTFUNC_SIGNATURE( RESET_MUTEX ),
  WASM_HOSTFUNC_SIGNATURE( GET_MUTEX_ID ),
  WASM_HOSTFUNC_SIGNATURE( GET_MUTEX_STATUS ),
  WASM_HOSTFUNC_SIGNATURE( GET_PROCESS_MUTEX_STATE ),
/* APEX (ARINC 653 Part 1): ERROR */
  WASM_HOSTFUNC_SIGNATURE( REPORT_APPLICATION_MESSAGE ),
  WASM_HOSTFUNC_SIGNATURE( CREATE_ERROR_HANDLER ),
  WASM_HOSTFUNC_SIGNATURE( GET_ERROR_STATUS ),
  WASM_HOSTFUNC_SIGNATURE( RAISE_APPLICATION_ERROR ),
  WASM_HOSTFUNC_SIGNATURE( CONFIGURE_ERROR_HANDLER ),

/* APEX (ARINC 653 Part 2: SAMPLING PORT EXTENSIONS */
  WASM_HOSTFUNC_SIGNATURE( READ_UPDATED_SAMPLING_MESSAGE ),
  WASM_HOSTFUNC_SIGNATURE( GET_SAMPLING_PORT_CURRENT_STATUS ),
  WASM_HOSTFUNC_SIGNATURE( READ_SAMPLING_MESSAGE_CONDITIONAL )
};

unsigned getNativeSymbols(NativeSymbol** _native_symbols)
{
  *_native_symbols = native_symbols;
  return sizeof(native_symbols)/sizeof(native_symbols[0]);
}
