// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: Copyright 2025 Airbus Defence and Space
// SPDX-FileContributor: Patrick Siegl <patrick.siegl@airbus.com>
// ARINC 653 Part 1: APEX Interface: SAMPLING PORT

#ifndef ARINC653_PART1_APEX_SAMPLING_PORT_WASM32
#define ARINC653_PART1_APEX_SAMPLING_PORT_WASM32

#include "arinc653_wasm32_helper.h"

/* APEX (ARINC 653 Part 1): SAMPLING PORT */
#define WASM32_SIGNATURE__CREATE_SAMPLING_PORT              "(iiiIii)"
#define WASM32_SIGNATURE__WRITE_SAMPLING_MESSAGE            "(iiii)"
#define WASM32_SIGNATURE__READ_SAMPLING_MESSAGE             "(iiiii)"
#define WASM32_SIGNATURE__GET_SAMPLING_PORT_ID              "(iii)"
#define WASM32_SIGNATURE__GET_SAMPLING_PORT_STATUS          "(iii)"

WASM32_HOST_FUNC_HEADER(CREATE_SAMPLING_PORT);
WASM32_HOST_FUNC_HEADER(WRITE_SAMPLING_MESSAGE);
WASM32_HOST_FUNC_HEADER(READ_SAMPLING_MESSAGE);
WASM32_HOST_FUNC_HEADER(GET_SAMPLING_PORT_ID);
WASM32_HOST_FUNC_HEADER(GET_SAMPLING_PORT_STATUS);

#endif /* #ifndef ARINC653_PART1_APEX_SAMPLING_PORT_WASM32 */
