// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: Copyright 2025 Airbus Defence and Space
// SPDX-FileContributor: Patrick Siegl <patrick.siegl@airbus.com>
// ARINC 653 Part 2: APEX Interface: SAMPLING PORT EXTENSION

#ifndef ARINC653_PART2_APEX_SAMPLING_PORT_EXTENSION_WASM32
#define ARINC653_PART2_APEX_SAMPLING_PORT_EXTENSION_WASM32

#include "arinc653_wasm32_helper.h"

/* APEX (ARINC 653 Part 2): SAMPLING PORT EXTENSIONS */
#define WASM32_SIGNATURE__READ_UPDATED_SAMPLING_MESSAGE     "(iiiii)"
#define WASM32_SIGNATURE__GET_SAMPLING_PORT_CURRENT_STATUS  "(iii)"
#define WASM32_SIGNATURE__READ_SAMPLING_MESSAGE_CONDITIONAL "(iIiiii)"

WASM32_HOST_FUNC_HEADER__iiiii(READ_UPDATED_SAMPLING_MESSAGE);
WASM32_HOST_FUNC_HEADER__iii(GET_SAMPLING_PORT_CURRENT_STATUS);
WASM32_HOST_FUNC_HEADER__iIiiii(READ_SAMPLING_MESSAGE_CONDITIONAL);

#endif /* #ifndef ARINC653_PART2_APEX_SAMPLING_PORT_EXTENSION_WASM32 */
