// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: Copyright 2025 Airbus Defence and Space
// SPDX-FileContributor: Patrick Siegl <patrick.siegl@airbus.com>
// ARINC 653 Part 1: APEX Interface: ERROR

#ifndef ARINC653_PART1_APEX_ERROR_WASM32
#define ARINC653_PART1_APEX_ERROR_WASM32

#include "arinc653_wasm32_helper.h"

/* APEX (ARINC 653 Part 1): ERROR */
#define WASM32_SIGNATURE__REPORT_APPLICATION_MESSAGE        "(iii)"
#define WASM32_SIGNATURE__CREATE_ERROR_HANDLER              "(iii)"
#define WASM32_SIGNATURE__GET_ERROR_STATUS                  "(ii)"
#define WASM32_SIGNATURE__RAISE_APPLICATION_ERROR           "(iiii)"
#define WASM32_SIGNATURE__CONFIGURE_ERROR_HANDLER           "(iii)"

WASM32_HOST_FUNC_HEADER__iii(REPORT_APPLICATION_MESSAGE);
WASM32_HOST_FUNC_HEADER__iii(CREATE_ERROR_HANDLER);
WASM32_HOST_FUNC_HEADER__ii(GET_ERROR_STATUS);
WASM32_HOST_FUNC_HEADER__iiii(RAISE_APPLICATION_ERROR);
WASM32_HOST_FUNC_HEADER__iii(CONFIGURE_ERROR_HANDLER);

#endif /* #ifndef ARINC653_PART1_APEX_ERROR_WASM32 */
