// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: Copyright 2025 Airbus Defence and Space
// SPDX-FileContributor: Patrick Siegl <patrick.siegl@airbus.com>
// ARINC 653 Part 1: APEX Interface: QUEUING PORT

#ifndef ARINC653_PART1_APEX_QUEUING_PORT_WASM32
#define ARINC653_PART1_APEX_QUEUING_PORT_WASM32

#include "arinc653_wasm32_helper.h"

/* APEX (ARINC 653 Part 1): QUEUING PORT */
#define WASM32_SIGNATURE__CREATE_QUEUING_PORT               "(iiiiiii)"
#define WASM32_SIGNATURE__SEND_QUEUING_MESSAGE              "(iiiIi)"
#define WASM32_SIGNATURE__RECEIVE_QUEUING_MESSAGE           "(iIiii)"
#define WASM32_SIGNATURE__GET_QUEUING_PORT_ID               "(iii)"
#define WASM32_SIGNATURE__GET_QUEUING_PORT_STATUS           "(iii)"
#define WASM32_SIGNATURE__CLEAR_QUEUING_PORT                "(ii)"

WASM32_HOST_FUNC_HEADER__iiiiiii(CREATE_QUEUING_PORT);
WASM32_HOST_FUNC_HEADER__iiiIi(SEND_QUEUING_MESSAGE);
WASM32_HOST_FUNC_HEADER__iIiii(RECEIVE_QUEUING_MESSAGE);
WASM32_HOST_FUNC_HEADER__iii(GET_QUEUING_PORT_ID);
WASM32_HOST_FUNC_HEADER__iii(GET_QUEUING_PORT_STATUS);
WASM32_HOST_FUNC_HEADER__ii(CLEAR_QUEUING_PORT);

#endif /* #ifndef ARINC653_PART1_APEX_QUEUING_PORT_WASM32 */
