// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: Copyright 2025 Airbus Defence and Space
// SPDX-FileContributor: Patrick Siegl <patrick.siegl@airbus.com>
// ARINC 653 Part 1: APEX Interface: PROCESS

#ifndef ARINC653_PART1_APEX_PROCESS_WASM32
#define ARINC653_PART1_APEX_PROCESS_WASM32

#include "arinc653_wasm32_helper.h"

/* APEX (ARINC 653 Part 1): PROCESS */
#define WASM32_SIGNATURE__GET_PROCESS_ID                    "(iii)"
#define WASM32_SIGNATURE__GET_PROCESS_STATUS                "(iii)"
#define WASM32_SIGNATURE__CREATE_PROCESS                    "(iii)"
#define WASM32_SIGNATURE__SET_PRIORITY                      "(iii)"
#define WASM32_SIGNATURE__SUSPEND_SELF                      "(Ii)"
#define WASM32_SIGNATURE__SUSPEND                           "(ii)"
#define WASM32_SIGNATURE__RESUME                            "(ii)"
#define WASM32_SIGNATURE__STOP_SELF                         "()"
#define WASM32_SIGNATURE__STOP                              "(ii)"
#define WASM32_SIGNATURE__START                             "(ii)"
#define WASM32_SIGNATURE__DELAYED_START                     "(iIi)"
#define WASM32_SIGNATURE__LOCK_PREEMPTION                   "(ii)"
#define WASM32_SIGNATURE__UNLOCK_PREEMPTION                 "(ii)"
#define WASM32_SIGNATURE__GET_MY_ID                         "(ii)"
#define WASM32_SIGNATURE__INITIALIZE_PROCESS_CORE_AFFINITY  "(iii)"
#define WASM32_SIGNATURE__GET_MY_PROCESSOR_CORE_ID          "(ii)"
#define WASM32_SIGNATURE__GET_MY_INDEX                      "(ii)"

WASM_HOST_FUNC_HEADER(GET_PROCESS_ID);
WASM_HOST_FUNC_HEADER(GET_MY_ID);
WASM_HOST_FUNC_HEADER(GET_PROCESS_STATUS);
WASM_HOST_FUNC_HEADER(CREATE_PROCESS);
WASM_HOST_FUNC_HEADER(SET_PRIORITY);
WASM_HOST_FUNC_HEADER(SUSPEND_SELF);
WASM_HOST_FUNC_HEADER(SUSPEND);
WASM_HOST_FUNC_HEADER(RESUME);
WASM_HOST_FUNC_HEADER(STOP_SELF);
WASM_HOST_FUNC_HEADER(STOP);
WASM_HOST_FUNC_HEADER(START);
WASM_HOST_FUNC_HEADER(DELAYED_START);
WASM_HOST_FUNC_HEADER(LOCK_PREEMPTION);
WASM_HOST_FUNC_HEADER(UNLOCK_PREEMPTION);
WASM_HOST_FUNC_HEADER(INITIALIZE_PROCESS_CORE_AFFINITY);
WASM_HOST_FUNC_HEADER(GET_MY_PROCESSOR_CORE_ID);
WASM_HOST_FUNC_HEADER(GET_MY_INDEX);

#endif /* #ifndef ARINC653_PART1_APEX_PROCESS_WASM32 */
